//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskApiNew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Quote
    {
        public string Id { get; set; }
        public QuoteType QuoteType { get; set; }
        public TaskType TaskType { get; set; }
        public string TaskDescription { get; set; }
        public Nullable<int> ContactId { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
    
        public virtual Personnel Contact { get; set; }
    }
}
